name: Deploy to S3 + CloudFront

on:
  push:
    branches: [ "main" ]

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Use Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 'lts/*'

      - name: Install dependencies
        working-directory: ./my-portfolio
        run: npm install 

      - name: Build project
        working-directory: ./my-portfolio
        run: npm run build

      - name: Deploy to S3
        uses: jakejarvis/s3-sync-action@master
        with:
          bucket: vardaankapoor.site
          region: us-east-2   # update with your region
          source-dir: dist
